### PR TITLE
Fix: historic stats loading

### LINKED ISSUE #158: Stats: play time chart doesn't show historic data
The play time chart is not being populated with historic data.

### PR DESCRIPTION
**Pull request by jamesjwarren**
This PR fixes #158, where to date was wrong in query.

### CODE REVIEW

File: tests/unit/stats/controllers/StatsCtrl.js [hunk 1]
```diff
@@ -140,8 +140,15 @@ describe("FM.stats.StatsCtrl", function() {
             $httpBackend.flush();
             $scope.playTime.data = [];
             $scope.playTime.labels = [];
+
+            StatsResource.get.calls.reset();
+            console.log(StatsResource.get.calls.count());
```
Comment (bcmrbvm) [inline tests/unit/stats/controllers/StatsCtrl.js]: I think you meant to remove this console log

**Comment by bcmrbvm** [comment]
other than the above looks good :+1:

File: tests/unit/stats/controllers/StatsCtrl.js (hunk 1 above)
Comment (jamesjwarren) [inline tests/unit/stats/controllers/StatsCtrl.js]: Thanks for spotting that
